### ISSUE TITLE
Raise error when values in specs are missing

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#281]
Not all parameters are given default values in the specs file (see #280). Raise an error when values are missing

**Comment by camiloramirezgo** [comment]
This feature introduced an error when the user wants to run the model in separate model preparation and running steps, as not all parameters are in the prep file, raising an error. I think it would be good to keep the possibility of running in different steps as that gives more flexibility for scenario development. If we go with that, then we need to find a way of avoiding the issue. One option would be to call the method later in the process, as before running the model to make sure all parameters needed are.
