### ISSUE TITLE
Modelling LPG Viability

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnSTOVE#3]
Given a set of points representing supply points (vector points or csv) and a friction map (raster). We want to determine the least-cost path between the supply points and every single cell in the settlement

**Comment by babakkhavari** [comment]
Idea:

1. Read supply points as geodataframe
2. Read friction map with rasterio
3. To avoid traveling across nodata cells, extract and exclude this value from the rasterio array
4. Find points that should be zero in the raster (start points)
5. Determine the least cost path from each start point 
6. Combine the different least-cost path arrays and choose the minimum value for each element

**Comment by babakkhavari** [comment]
`import numpy as np
import pandas as pd
from skimage.graph import MCP, route_through_array
from functions import *

# This map represents the travel speed from this allocation process, expressed in units of minutes 
# required to travel one metre.
friction = r"C:\Proposals\CCA\LPG_CODE_TEST_LAYERS\Friction layer.tif"
# Startpoints
supply_points = r"C:\Proposals\CCA\LPG_CODE_TEST_LAYERS\LPG_start.shp"
#AOI
mask = r"C:\Proposals\CCA\gadm36_NPL_shp\gadm36_NPL_0.shp"

def friction_start_points(friction, in_points, out_raster):
    start = gpd.read_file(in_points)
    row_list = []
    col_list = []
    with rasterio.open(friction) as src:  
        arr = src.read(1)
        for index,row in start.iterrows():
            rows, cols = rasterio.transform.rowcol(src.transform, row["geometry"].x, row["geometry"].y)
            arr[rows][cols] = 0
        
            out_meta = src.meta
               
            row_list.append(rows)
            col_list.append(cols)
        
    with rasterio.open(out_raster, 'w', **out_meta) as dst:
        dst.write(arr, indexes = 1)
        dst.close()
        
    return row_list, col_list

#Finding start points
row, col = friction_start_points(friction, supply_points, new_friction)

#Creating array that will be used in dijkstra
with rasterio.open(friction) as src:  
        arr = src.read(1)
friction_map=rasterio.open(friction)
nodata_fric = friction_map.nodata

#Adding statvalues
pointlist = []
i = 0
for test in row:
    positiions = (row[i],col[i])
    pointlist.append(positiions)
    i = i+1

rows = np.arange(arr.shape[0])
cols = np.arange(arr.shape[1])
pointlist[1]
weight = []
for r in rows:
        for c in cols:
            if arr[r][c] != nodata_fric:
                index, weight_i = route_through_array(arr, pointlist[1], (r,c))
                weight.append(weight_i)`

This code takes way to long to run. Can it be sped up?

**Comment by camiloramirezgo** [comment]
I think the problem is that we are looping through each row and column, to give that as the ending point. This is very inefficient and actually not needed as we can pass a set of end points and the algorithm will calculate the least-cost path from the given starting points to all of the end points. If no end points are provided, then the least-cost path is calculated for all cells. An example below:
```python
import rasterio
import numpy as np
from skimage.graph.mcp import MCP
import matplotlib.pyplot as plt

# I read my base layer "population" and based on it shape I create a random cost surface (just because I don't have the friction layer)
base_layer = 'data/population_npl_2018-10-01_1km.tif'
with rasterio.open(base_layer) as src:
    population = src.read(1)

rows = population.shape[0]
cols = population.shape[1]
image = np.random.uniform(1, 100, rows * cols).reshape((rows, cols))

#Then I assign a very big number to the no data value thus the cost path never goes through a no data cell
image[population==-9999] = float('inf')

#Create the MCP object with the image, in this case I am using fully_connected to allow diagonal steps
mcp = MCP(image, fully_connected=True)

#Call the find_costs method specifying the start points (this should be the LPG suppliers indexes in the raster) and optionally end points, 
#which can be an array of population cells. However, if end points are not passed then it will calculate the least cost path to every cell, which also works
cumulative_costs, traceback = mcp.find_costs(starts=[[100, 223], [400, 500], [400, 700]])

#the cumulative_costs is what we want, this is a new image containing the cost to get to every cell from the nearest (least cost) start point. You can plot it like
fig, ax = plt.subplots(1,1, figsize=(16, 9))
plt.imshow(cumulative_costs)

#then you can trace the least cost path to any point by doing
trace = mcp.traceback([200, 223])
indx = np.array(trace).T

#and even create a new raster with the path (just to visualize not actually needed).
path = np.zeros(image.shape)
path[indx[0], indx[1]] = 1
path[population==-9999] = np.nan
fig, ax = plt.subplots(1,1, figsize=(16, 9))
plt.imshow(path)
```
The `cumulative_costs` would look like:
![image](https://user-images.githubusercontent.com/12953752/116520411-fa3f8f00-a8d2-11eb-8b73-fada21b08e3a.png)

And the path:
![image](https://user-images.githubusercontent.com/12953752/116520455-0b889b80-a8d3-11eb-9d7c-a0cfefba4242.png)
