### ISSUE TITLE
citation to add: Khavari et al (2023)

### ISSUE THREAD

**Issue by robbiemorrison** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#316]
The developers might consider adding this recent citation to the `README.md` file:

- Khavari, Babak, Camilo Ramirez, Marc Jeuland and Francesco Fuso Nerini (12 January 2023).  ["A geospatial approach to understanding clean cooking challenges in sub-Saharan Africa"](https://www.nature.com/articles/s41893-022-01039-8.pdf).  *Nature Sustainability*.  1–11.  ISSN [2398-9629](https://www.worldcat.org/issn/2398-9629).  doi:[10.1038/s41893-022-01039-8](https://doi.org/10.1038/s41893-022-01039-8). Creative Commons CC‑BY‑4.0 license.

**Comment by babakkhavari** [comment]
Thank you for the heads-up this has now been added.
