### ISSUE TITLE
Create training material

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#326]
- [x] Installation instructions OnStove - the different versions
- [x] Lecture 0 - Intro to the course objectives and structure
- [x] Lecture 1 - General clean cooking
- [x] Lecture 2 - BAR-HAP Marc
- [x] Lecture 3 - OnStove deep-dive
- [x] Lecture 4 - What to present in a ppt
- [x] Exercise 1 - CCE
- [x] Exercise 2 - Data collection (GIS)
- [x] Exercise 3 - GIS processes in OnStove
- [x] Exercise 4 - Data collection (non-GIS)
- [x] Exercise 5 - Calibration
- [x] Exercise 6 - Running scenarios
- [x] Exercise 7 - Visualize results

**Comment by camiloramirezgo** [comment]
# Lecture 0
* Introduce the course, give course objectives and structure (30 minutes)

**Comment by camiloramirezgo** [comment]
# Lecture 1
* An introduction to clean cooking (1:30 hour):
    * What is clean cooking?
         * WHO definition
         * Traditional stoves
         * ICS
    * What is the current situation
         * How many people lack clean cooking 
         * Where is the problem most pronounced
         * Historical progress
         * Outlook
    * How does clean cooking affect other sustainable development goals
        * Health
        * Gender
        * Poverty
        * Climate action
   * What are the barriers to clean cooking?
   * What is GIS (recap of the first three days) and how can it be used for clean cooking analysis
   * Light introduction to OnStove (a more detailed introduction comes later)
        * What is the tool?
        * What are the needed inputs?
        * What are the steps of running the analysis?
        * What are the expected results of the analysis?
        * What has been done with the tool? (Africa and Nepal papers, end with EAE Nepal)

**Comment by camiloramirezgo** [comment]
# Lecture 4: Deep dive on all the benefits and costs included in the tool
* Why are these benefits and costs included?
* Why are certain benefits and costs not included, and what is the impact of this?
* How are the benefits calculated and why?
* How are costs calculated and why?

**Comment by camiloramirezgo** [comment]
# Exercise 2 - Data collection (GIS)
* First part lecture about GIS data sources, where to find data and data formats.
* Hands-on exercise on getting data for their countries, and simple exploration of data and visualization on QGIS.
* Hands-on exercise on GIS data processing with OnStove (show step by step with visualization and relating back to what have been learned in the morning sessions)

**Comment by camiloramirezgo** [comment]
# Exercise 4 - Data collection (non-GIS)
Calibration is the second step of OnStove. Here the total, urban and electrified populations are calibrated, as well as the current mix of cooking fuels. This will be done through the notebook step-by-step by a tutor, stopping after each step to ensure everyone is following along. Some of the theories used will be discussed along the way (i.e., how do we calibrate electrified population, why is it important to know who cooks with what etc.)

**Comment by camiloramirezgo** [comment]
# Exercise 6 - Running scenarios
* Run different scenarios changing some input data such as fuel costs, investment costs, technologies, and adding subsidies?  
* Step 3 of the notebook.

**Comment by camiloramirezgo** [comment]
# Exercise 7 - Visualize results
* Play around with different map visualization from the tool
* Step 4 in the notebook.
