### ISSUE TITLE
Contingency plans

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#330]
Come up with contingency plans for everything in #326. What do we do if we have time left, if Marc is not available, if certain participants have problems reaching different milestones?

**Comment by camiloramirezgo** [comment]
Create a back-up for the data repository, it should be one online (google drive or OndeDrive) and one offline (usb).

**Comment by camiloramirezgo** [comment]
Create an offline installable version of the package, look at #289
