### ISSUE TITLE
Bring ReadTheDocs up to date

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#337]
- [x] We need to remove the link to mybinder as it is not working right now, se more at #323
- [x] This line in the quick start of the docs needs fixing: `env create –name onstove –file jupyter_env.yaml`, this nees to be `env create -n onstove –f envs/jupyter_env.yaml`
- [x] Improve docs of [`align_layers`](https://onstove-documentation.readthedocs.io/en/latest/generated/onstove.DataProcessor.align_layers.html) method, adding link to the `align` method of the `RasterLayer` class in the see also. Remove the current link to the `add_layer` method there
- [x] Make sure the examples of input data files (soc_specs and tech_specs) cotain all data with updated names
- [x] We should improve documentation for the `read_scenario_data` and the `read_tech_data` methods, with links to example files and information on the parameters
- [x] Add publication to the `Resources and license` page
- [x] Create a page on readthedocs for collaborations
- [x] Update documentation on all plotting methods, both from the `model.py` and the `layer.py`
- [x] make `check_scenario_data`, `techshare_sumtoone`, `ecooking_adjustment`, `pop_tech`, `techshare_allocation` and `biogas_adjustments` a private method

**Comment by camiloramirezgo** [comment]
We need to remove the link to mybinder as it is not working right now, se more at #323

**Comment by babakkhavari** [comment]
- [ ] `read_scenario_data`
- [ ]
