### ISSUE TITLE
Improve step one of the notebook

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#339]

**Comment by babakkhavari** [comment]
Fixed

- Explaining texts
- File downloads
- Added additional cells when needed. 

Test it for bugs and make sure that the explaining text is correct

**Comment by camiloramirezgo** [comment]
When we make the release, we will need to remove the `sys.path.append("..")` line and the autoreloads. We will also need to update the paths as `output_directory = '../example/results'` I spect the behaviour to be that the user will be able to just download the example notebook, install onstove with conda and run the notebook directly being in the same directory. So the `../example` won't be really required.

**Comment by camiloramirezgo** [comment]
I want to "hide" the data download steps into a function that gets called with the country as input only. We can put this function on a `utils.py` file in the example and import it. I think this will make the notebook cleaner and will avoid confusion among the participants about those download steps.

**Comment by camiloramirezgo** [comment]
Thing done:
* Reviewed and comlemented text
* Fixed one link to documentation that was wrong
* Added links to the sections in the description of the notebook
* Added links at the end of each section to be able to go back to the top of the notebook
* Rearrange order of the `mask_all` and `aling_all` methods
* Moved the description of each dataset to the section where it is read rather than at the begining of the data processing section
* Moved the `DataProcessor` creation to the data processing step, and left the definition of the `output_directory` to the begining of the notebook
