### ISSUE TITLE
Improve step two of the notebook

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#340]

**Comment by babakkhavari** [comment]
Step 2.3 crashes with the following error code:

`KeyError: 'rural_hh_size'`

if we use the same files as for the SSA paper, make sure to update the specs files that are uploaded on the training mendeley

**Comment by babakkhavari** [comment]
Changing the data for now leaving the code as is

**Comment by camiloramirezgo** [comment]
Things done:
* Reviewed and complemented text
* Added links to descriptions of some python datastructure as dictionaries and dataframes (when mentioned for the first time)
* Added option to `raster_to_dataframe` to be able to pass either a `RasterLayer` or a `str` path, so we don't have to create a `RasterLayer` to read in the nighttime lights

**Comment by camiloramirezgo** [comment]
I think we should simplify the names used for the technologies, or at least standardize them as for some we use underscores and other spaces. We can make it cleaner as just doing `Biomass ICS ND` instead of `Collected_Improved_Biomass` or something similar.
