### ISSUE TITLE
Improve step 3 of the notebook

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#341]

**Comment by babakkhavari** [comment]
Even after removing a print statement it prints out a zero, I am not sure why:



![Image](https://user-images.githubusercontent.com/35455877/236242993-4e51246e-9457-42b3-8617-f34b6447dcdb.png)

**Comment by babakkhavari** [comment]
Similar to the `rural_hh_size` and `urban_hh_size`, make sure that we have `cost_of_carbon_emissions` rather than the current `cost of carbon emissions` in the files

**Comment by babakkhavari** [comment]
These error should be fixed now as well

**Comment by camiloramirezgo** [comment]
Things done:
* Added `"."` as the default value of `output_directory` in the main model class, so we don't have to specify it in the begining of step 3.
