### ISSUE TITLE
Testing the package for first conda-forge release

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#345]
- [x] remove cero printing after maximum tech benefit calculation
- [x] check alignment problem in the background map
- [x] check on histogram plotting for faceting option
- [ ] `save_layer` in `add_layer` from `DataProcessor` is not clear
- [x] An `invalid value encountered in cast` error is happening with the `raster_to_dataframe` method. This is explained in 
- [x] #352 
- [x] Improve message from baseline calibration in run (look messy now) Camilo
- [x] Adjust default spacing in the legend of the map
- [x] Add option to save plots in `png` format and make that the default

**Comment by babakkhavari** [comment]
For the first point: I think it is line 1770 in model.py of the main branch. If we remove that the zero should be gone

**Comment by babakkhavari** [comment]
For `add_layer` we have the option of selecting `normalization`, but the only option for `normalization `is `MinMax` in `RasterLayer.normalization`, should we change that to a boolean?

**Comment by babakkhavari** [comment]
Could we stop this from happening?

**Comment by babakkhavari** [comment]
warning when coordinate system has another unit than meters

**Comment by babakkhavari** [comment]
`add_mask_layer` only accepts vectors, which is fine, but maybe we can print a warning if the type is different than what is OK?

**Comment by babakkhavari** [comment]
If someone runs the cell `get_capactíty_cost` without running the cell that reads in the model data in between it crashes. This is as far as I can see the only cell with this behavior. Worth doing something abt it?

![Image](https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/assets/35455877/d4a4db13-5a02-4726-a899-24b39ee6cfc5)

**Comment by babakkhavari** [comment]
In `recalibrate_livestock` we force people to include all livestock, would it make sense to let people use a selection?

**Comment by babakkhavari** [comment]
Is this in percentage or ratio? i.e. is the max 100 or 1?

![Image](https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/assets/35455877/23b387c0-d67b-4f2a-9746-9f01fd182676)

**Comment by babakkhavari** [comment]
`population_to_dataframe` creates the dataframe, while all other raster layers are extracted to it. Would it make sense for the other extraction functions to check whether the dataframe exists and create it if not? So that you can call the extraction functions in what ever order you like?

**Comment by babakkhavari** [comment]
Does it make sense to remove cells with less than 1 household?

**Comment by babakkhavari** [comment]
![Image](https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/assets/35455877/0f99c9d1-9d9d-451c-b702-911fe7613413)

Change this to emission costs avoided
